### ISSUE TITLE
AttributeError:Datasets' object has no attribute 'training_data

### ISSUE THREAD

**Issue by Harold-Zhang** [matex-org/matex#6]
I tested the code from _/matex/src/deeplearning/tensorflow/examples/glibc_after_2.19/MNIST/tf_lenet3.py_ with command `python tf_lenet3.py` and I got an error:
```Traceback (most recent call last):
  File "tf_lenet3.py", line 17, in <module>
    mnist = tf.DataSet("MNIST", normalize=255.0)
AttributeError: module 'tensorflow' has no attribute 'DataSet'```

Then, I modified the code. I added `from tensorflow.examples.tutorials.mnist import input_data` and `mnist = input_data.read_data_sets('MNIST_data', one_hot=True)`, removed `mnist = tf.DataSet("MNIST", normalize=255.0)` and I got the following error:
```
Traceback (most recent call last):
  File "tf_lenet3.py", line 70, in <module>
    for train_batch in range(int(len(mnist.training_data)/args.train_batch)):
AttributeError: 'Datasets' object has no attribute 'training_data'
```
What should I do to solve the problem?
@jeffdaily @vamatya @abhinavvishnu @charlesmsiegel @cabe1980 Thanks for your help!

**Comment by charlesmsiegel** [comment]
Our DataSet class and the Tensorflow Datasets class do not have compatible interfaces.  Which version of the code are you using?  Could you post the contents of your /mates/src/deeplearning/tensorflow/gpu/py3.x/py_distro/lib/python3.5/site-packages/tensorflow/__init__.py  (or appropriate analogue if using cpu version)?
